# Website Builder - Netlify Configuration
# Professionelle No-Code-Plattform

# Build Configuration
[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm run build"

# Node.js Version
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Function Configuration
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["zod"]

# API Redirects - Clean URLs für bessere UX
[[redirects]]
  from = "/api/ping"
  to = "/.netlify/functions/ping"
  status = 200
  force = true

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200
  force = true

[[redirects]]
  from = "/api/generate"
  to = "/.netlify/functions/generate"
  status = 200
  force = true

[[redirects]]
  from = "/api/projects/*"
  to = "/.netlify/functions/projects/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/analyze"
  to = "/.netlify/functions/analyze"
  status = 200
  force = true

[[redirects]]
  from = "/api/assets/*"
  to = "/.netlify/functions/assets/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/publish/*"
  to = "/.netlify/functions/publish/:splat"
  status = 200
  force = true

# SPA Fallback - für Client-side Routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://fonts.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://fonts.gstatic.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api.openai.com;"

# API Headers - CORS für Frontend
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Max-Age = "86400"

# Static Asset Caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Font Caching
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment Variables (für Production)
[context.production.environment]
  NODE_ENV = "production"
  OPENAI_MODEL = "gpt-4o-mini"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"

# Edge Functions (für zukünftige Features)
[[edge_functions]]
  function = "middleware"
  path = "/*"

# Rate Limiting Edge Function
[[edge_functions]]
  function = "rate-limit"
  path = "/api/*"

# Development Settings
[dev]
  command = "npm run dev:simple"
  port = 3000
  publish = "public"
  functions = "netlify/functions"
