# Website Builder - Netlify Configuration

[build]
  publish = "public"
  functions = "netlify/functions"
  command = "echo 'Build completed'"

[build.environment]
  NODE_VERSION = "18"

# API Redirects
[[redirects]]
  from = "/api/ping"
  to = "/.netlify/functions/ping"
  status = 200

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/api/generate"
  to = "/.netlify/functions/generate"
  status = 200

[[redirects]]
  from = "/api/projects/*"
  to = "/.netlify/functions/projects/:splat"
  status = 200

# SPA Fallback entfernt - verursacht iframe-Probleme

# Basic Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"

# Erlaube iframe für preview.html
[[headers]]
  for = "/preview.html"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"